{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.react",
    "module": "hermes-android",
    "version": "0.71.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hermes-android-0.71.12-debug.aar",
          "url": "hermes-android-0.71.12-debug.aar",
          "size": 9393421,
          "sha512": "8f2f694feaf2860edb1d167fb2d9ef552871918c23e38c451dc0d62477e2d6fad4c4bbb4642f073eea6880c8426bb8724e8ce6302f225792a688e7b8db937217",
          "sha256": "652830caf8bdfd8674e47ff44349e21d56c654ab7807e4b23b4205da37c3f190",
          "sha1": "f653a42e74519249f6d66dc8392c39c05e3822fb",
          "md5": "51ccda0395c2ff5170c98289ffc13627"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hermes-android-0.71.12-debug.aar",
          "url": "hermes-android-0.71.12-debug.aar",
          "size": 9393421,
          "sha512": "8f2f694feaf2860edb1d167fb2d9ef552871918c23e38c451dc0d62477e2d6fad4c4bbb4642f073eea6880c8426bb8724e8ce6302f225792a688e7b8db937217",
          "sha256": "652830caf8bdfd8674e47ff44349e21d56c654ab7807e4b23b4205da37c3f190",
          "sha1": "f653a42e74519249f6d66dc8392c39c05e3822fb",
          "md5": "51ccda0395c2ff5170c98289ffc13627"
        }
      ]
    },
    {
      "name": "debugVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-android-0.71.12-debug-sources.jar",
          "url": "hermes-android-0.71.12-debug-sources.jar",
          "size": 62707,
          "sha512": "b6d659b87a103dd21026d8715420d047b70e76219d39121795598811cff2c7bb6cf3a860d8836fe6eeb753f785d7c2f7b961ea48c5cba27626a6e1cb5b07ee62",
          "sha256": "1fe6791aeefb0391d319d763c655a6f8232676141b886d0a467b8834a0b86497",
          "sha1": "75340c383a5d55a37d68181f12b1d8d939a3f065",
          "md5": "7b864274b543d21ee7d7c9c8e7f7b043"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hermes-android-0.71.12-release.aar",
          "url": "hermes-android-0.71.12-release.aar",
          "size": 7557898,
          "sha512": "f431e318a579e8dcf8bf74a965765e03d8b89c8346862b26c61828c88c3e176cd1f47bcb9d98636b0fa5e71dc226b85b830ccc1cbc681669932fa5a701250e6e",
          "sha256": "677b44db5b159e9b5a18cb51de47ce1841b12c211e915d93854f66e6f29ca9dd",
          "sha1": "7b706e9db006e230ba7f4a1aadf2293b583fbb2a",
          "md5": "587e0a9e8911eaa487a10e1dc615ad34"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hermes-android-0.71.12-release.aar",
          "url": "hermes-android-0.71.12-release.aar",
          "size": 7557898,
          "sha512": "f431e318a579e8dcf8bf74a965765e03d8b89c8346862b26c61828c88c3e176cd1f47bcb9d98636b0fa5e71dc226b85b830ccc1cbc681669932fa5a701250e6e",
          "sha256": "677b44db5b159e9b5a18cb51de47ce1841b12c211e915d93854f66e6f29ca9dd",
          "sha1": "7b706e9db006e230ba7f4a1aadf2293b583fbb2a",
          "md5": "587e0a9e8911eaa487a10e1dc615ad34"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-android-0.71.12-release-sources.jar",
          "url": "hermes-android-0.71.12-release-sources.jar",
          "size": 62694,
          "sha512": "205a0fd395d6d02c27c4611ae1ceca7ccb4f3554f17f44d338f9ffef2e3521e933616e74ac1b17bb7d300891ede5ecf58e966a11becda27f6760f862f2316783",
          "sha256": "e622d9a7db5ba1a2161785ab8745dda58d1012aad04f7f9489fce207cf567f8a",
          "sha1": "34cf662170d553da87ddd8ef2213f13212955d1d",
          "md5": "c8db891c3be1b407d7079c02c303243b"
        }
      ]
    }
  ]
}
